version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
        prefix: "deps:"
    reviewers:
      - "Cyb3r-Jak3"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
        prefix: "deps:"
    reviewers:
        - "Cyb3r-Jak3"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
        prefix: "deps:"
    reviewers:
      - "Cyb3r-Jak3"
