name: golangci-lint
on:
  push:
    paths:
      - '**.go'
      - 'go.sum'
      - 'go.mod'
    tags-ignore:
      - "v*"
  pull_request:
    branches:
      - master
permissions:
  contents: read

jobs:
  golangci:
    name: golangci linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6 # https://github.com/marketplace/actions/run-golangci-lint
        with:
          version: latest
